markdown : fix "AttributeError: 'EntryPoints' object has no attribute 'get'"
https://python-markdown.github.io/changelog/#342-2023-03-22
3.4.2 is compatible with Python 3.11
3.10.0 with Python 3.14
No in between Python version announced, so picking 3.14

No change to be made in Tracim code as we are only using markdown.markdown()